MLOPS-473 Add download scripts and config files.
NoMagicAi/video-item-tracking pull request #1
Opened 2022-10-06 14:24 UTC by ksztenderski

Signed-off-by: Krystian Sztenderski <sztenderskikrystian@nomagic.ai>

2022-10-12 14:28 UTC, kamildec requested changes

2022-10-12 14:28 UTC, kamildec commented on scripts/download_cvat.py
> +STAGING_API_URL = "https://demeter-cvat.staging.nomagic.io/api/v1"
Might be a good idea to choose version by passing proper flag when running script.

2022-10-12 14:37 UTC, kamildec commented on README.md
>  # Video Item Tracking
Please add info about how to run provided scripts so all datasets are placed in the correct directory.

2022-10-14 10:52 UTC, ksztenderski commented on .flake8
> +extend-ignore = E203
done

2022-10-14 10:52 UTC, ksztenderski commented on .gitignore
> +!datasets/README.md
done

2022-10-14 10:52 UTC, ksztenderski commented on scripts/download_ovis.sh
> +get_dataset "valid"
done

2022-10-14 10:52 UTC, ksztenderski commented on pyproject.toml
> +line-length = 120
done

2022-10-14 10:53 UTC, ksztenderski commented on requirements.txt
> +types-pytz==2022.2.1
done

2022-10-14 11:16 UTC, ksztenderski commented on scripts/download_coco.sh
> +        wget -c "${download_paths[$1]}" --no-warc-keep-log
I didn't know this sw. I gave it a try on `http://images.cocodataset.org/annotations/annotations_trainval2017.zip`. And here are my timing results:
```
wget: 1m21,335s
axel -n 10: 1m5,454s
axel: 1m10,212s (no -n specified, created 4 connections)
axel -n 8: 0m59,131s
axel -n 16: 1m2,123s
```

I assume the number of connections you've chosen was arbitrary. I myself am a fan of powers of 2, so I changed it to 8. But maybe you know how is the number of connections chosen by default, I'd guess that it depends on the size of the file, maybe it is most optimal to not specify it?

2022-10-14 11:37 UTC, ksztenderski commented on scripts/download_cvat.py
> +        """Add annotation entry. Annotation contains both segmentation mask polygon points and bbox. By default we save
done

2022-10-14 11:37 UTC, ksztenderski commented on scripts/download_cvat.py
> +            password (str): Password to login to CVAT.
Changed to "log in".

2022-10-14 11:43 UTC, ksztenderski commented on scripts/download_cvat.py
> +STAGING_API_URL = "https://demeter-cvat.staging.nomagic.io/api/v1"
done

2022-10-14 12:04 UTC, ksztenderski commented on README.md
>  # Video Item Tracking
done

2022-10-15 10:16 UTC, kamildec commented on scripts/download_coco.sh
> +        wget -c "${download_paths[$1]}" --no-warc-keep-log
10 connections are chosen often when `axel` is compared to `wget` on many different community forums. According to your analysis, 8 works fine too so I don't insist on the number of connections.

2022-10-15 11:11 UTC, kamildec approved these changes

2022-10-15 15:08 UTC, kamildec commented on requirements.txt
> +types-pytz==2022.2.1
Please add `axel` to requirements

2022-10-15 16:17 UTC, kamildec requested changes

2022-10-15 16:17 UTC, kamildec commented on scripts/download_cvat.py
> +        self._categories_list: List[dict[str, Any]] = []
Please replace `dict` type annotation with `Dict` from `typing` library.

2022-10-17 08:10 UTC, ksztenderski commented on scripts/download_cvat.py
> +        self._categories_list: List[dict[str, Any]] = []
We use Python 3.9 (in Nomagic), it is not explicitly said yet in this repository, but when I'll set up a docker for it, we will use Python 3.9. And since Python 3.9 ([PEP 585](https://peps.python.org/pep-0585/)) all built in types are generic and importing those from `typing` is deprecated.

2022-10-19 12:34 UTC, merged